import { SignalCellularNullOutlined } from "@mui/icons-material";
import { ImageIconProps } from "~/types";

export const imageIconData: Array<ImageIconProps> = [
  {
    size: "m",
    color: "red",
    title: "Lead",
    image: "/lead.jpg",
    image2: null,
    multiple: false,
    link: "/lead",
  },
  {
    size: "m",
    color: "green",
    title: "Project",
    image: "/project_lead.jpg",
    image2: null,
    multiple: false,
    link: "/project",
  },
  {
    size: "m",
    color: "blue",
    title: "Backend",
    image: "/backend_lead.jpg",
    image2: null,
    multiple: false,
    link: "/backend",
  },
  {
    size: "m",
    color: "yellow",
    title: "Frontend",
    image: "/frontend_lead.jpg",
    image2: null,
    multiple: false,
    link: "/frontend",
  },
  {
    size: "m",
    color: "blue",
    title: "Education",
    image: "/education_lead1.jpg",
    image2: "/education_lead2.jpg",
    multiple: true,
    link: "/education",
  },
  {
    size: "m",
    color: "yellow",
    title: "Agile",
    image: "/agile_lead.jpg",
    image2: null,
    multiple: false,
    link: "/agile",
  },
  {
    size: "m",
    color: "red",
    title: "Outreach",
    image: "/outreach_lead.jpg",
    image2: null,
    multiple: false,
    link: "/outreach",
  },
  {
    size: "m",
    color: "green",
    title: "Operations",
    image: "/operations_lead.jpg",
    image2: null,
    multiple: false,
    link: "/operations",
  },
  {
    size: "m",
    color: "red",
    title: "Marketing",
    image: "/marketing_lead.jpg",
    image2: null,
    multiple: false,
    link: "/marketing",
  },
  {
    size: "m",
    color: "yellow",
    title: "Finance",
    image: "/finance_lead.jpg",
    image2: null,
    multiple: false,
    link: "/finance",
  },
];
